import requests
def get_exp(ghId,actid):
    headers = {
        'Accept': 'application/json, text/plain, */*',
        'Accept-Language': 'zh-CN,zh;q=0.9',
        'Authorization': 'eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOjczNjc5ODcyLCJleHAiOjE2ODMyMTE3MDh9.5pTh5ABVeVqmVGu8pZEsrhuCBk0Z33priU2SxFE3BIUi2BxwIiHxX7-rGupqQQMog7JsbaH_vkLuWH67vWCG6A',
        'Connection': 'keep-alive',
        'Content-Type': 'application/json',
        'Origin': 'https://pro.qunjielong.com',
        'Referer': 'https://pro.qunjielong.com/',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-site',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36',
        'feature-tag': '',
        'ghId': ghId,
        'sec-ch-ua': '"Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'uid': '73679872',
    }
    #2304080314677906
    #'PsHG7Z8_bsSfpBS_13418e71'
    json_data = {
        'exportModel': 'CUSTOMIZED',
        'exportDimension': 'ORDER_EACH_ROW',
        'aggregateSamePersonOrder': False,
        'deleteZeroProductOrder': True,
        'sameActOrderGroup': False,
        'resultHandleType': 'PRE_VIEW',
        'currentGhId': ghId,
        'actId': actid,
        'ghId': ghId,
        'ghViewType': 20,
        'customerOrderQueryParamDTO': {
            'actId': actid,
            'status': 0,
            'orderNoList': [],
            'dlvAddrId': 0,
            'logisticsNoList': [],
            'merchantGhCodeList': [
                '0',
            ],
            'actType': 30,
            'refundStatus': 0,
            'activityType': 30,
            'verify': 'eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOjczNjc5ODcyLCJleHAiOjE2ODMyMTE3MDh9.5pTh5ABVeVqmVGu8pZEsrhuCBk0Z33priU2SxFE3BIUi2BxwIiHxX7-rGupqQQMog7JsbaH_vkLuWH67vWCG6A',
            'forward': False,
            'orderNos': '',
            'ghId': ghId,
            'isCustomOrder': True,
            'isAllActExport': False,
            'ghViewType': 20,
            'asStatusList': None,
            'needPassword': False,
        },
        'orderTypeExportEnum': 'NORMAL_PC_ORDER',
        'fieldList': [
            {
                'name': 'logisticsCompany',
                'desc': '快递公司',
                'example': '圆通快递',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 5,
            },
            {
                'name': 'logisticsNo',
                'desc': '快递单号',
                'example': 'YT504056233988',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 10,
            },
            {
                'name': 'orderNo',
                'desc': '订单号',
                'example': '1145324',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 15,
            },
            {
                'name': 'activityName',
                'desc': '活动名称',
                'example': '活动名称',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 20,
            },
            {
                'name': 'pactNo',
                'desc': '下单序号',
                'example': '1',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 25,
            },
            {
                'name': 'actNo',
                'desc': '接龙号',
                'example': '1',
                'selected': True,
                'simpleModelDefault': True,
                'sortNum': 30,
            },
            {
                'name': 'sactNo',
                'desc': '帮卖团长接龙号',
                'example': '帮卖团长接龙号',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 35,
            },
            {
                'name': 'nickname',
                'desc': '微信昵称',
                'example': '小明',
                'selected': True,
                'simpleModelDefault': True,
                'sortNum': 40,
            },
            {
                'name': 'linkMan',
                'desc': '收货人',
                'example': '王小明',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 45,
            },
            {
                'name': 'linkPhone',
                'desc': '联系电话',
                'example': '13700000000',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 50,
            },
            {
                'name': 'goodsCount',
                'desc': '商品合计',
                'example': '苹果(500g)*1\r\n香蕉(1斤)*2',
                'selected': True,
                'simpleModelDefault': True,
                'sortNum': 55,
            },
            {
                'name': 'costPrice',
                'desc': '批发价总金额',
                'example': '10.0',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 65,
            },
            {
                'name': 'commissionPrice',
                'desc': '已发放佣金',
                'example': '10.0',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 70,
            },
            {
                'name': 'carriagePrice',
                'desc': '订单运费',
                'example': '10.0',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 75,
            },
            {
                'name': 'refundCarriagePrice',
                'desc': '订单已退运费',
                'example': '5.0',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 77,
            },
            {
                'name': 'totalPrice',
                'desc': '订单总金额',
                'example': '10.0',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 85,
            },
            {
                'name': 'refundPrice',
                'desc': '已退金额',
                'example': '10.0',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 90,
            },
            {
                'name': 'payStatus',
                'desc': '支付状态',
                'example': '已支付',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 95,
            },
            {
                'name': 'discountFee',
                'desc': '优惠金额（¥）',
                'example': '10.0',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 95,
            },
            {
                'name': 'orderStatus',
                'desc': '订单状态',
                'example': '未发货',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 100,
            },
            {
                'name': 'signStatus',
                'desc': '签到状态',
                'example': '未签到',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 105,
            },
            {
                'name': 'groupStatus',
                'desc': '拼团状态',
                'example': '已成团',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 110,
            },
            {
                'name': 'trackStatusStr',
                'desc': '物流状态',
                'example': '待揽件,顺丰快递:SF123254521;',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 110,
            },
            {
                'name': 'exportStatus',
                'desc': '导单状态',
                'example': '已导单',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 111,
            },
            {
                'name': 'dealTime',
                'desc': '下单时间',
                'example': '2020/05/26 10:28',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 115,
            },
            {
                'name': 'refundStatus',
                'desc': '售后状态(旧)',
                'example': '待退款',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 140,
            },
            {
                'name': 'orderRefundStatus',
                'desc': '退款状态',
                'example': '部分退款',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 141,
            },
            {
                'name': 'refundFinishTime',
                'desc': '退款完成时间',
                'example': '2023/02/26 10:28',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 155,
            },
            {
                'name': 'orderTags',
                'desc': '订单标签',
                'example': '大客户,待退款',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 159,
            },
            {
                'name': 'province',
                'desc': '省',
                'example': '广东省',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 186,
            },
            {
                'name': 'city',
                'desc': '市',
                'example': '广州市',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 187,
            },
            {
                'name': 'country',
                'desc': '区',
                'example': '天河区',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 188,
            },
            {
                'name': 'address',
                'desc': '收货地址',
                'example': '广东省广州市海珠区T.I.T创意园',
                'selected': True,
                'simpleModelDefault': True,
                'sortNum': 196,
            },
            {
                'name': 'route',
                'desc': '所属路线',
                'example': '一号线',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 206,
            },
            {
                'name': 'dlvName',
                'desc': '所属提货点',
                'example': 'T.I.T创意园',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 216,
            },
            {
                'name': 'dlvAddress',
                'desc': '所属提货点地址',
                'example': '广州市海珠区客村T.I.T创意园',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 220,
            },
            {
                'name': 'dlvContactName',
                'desc': '提货点联系人',
                'example': '李小红',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 226,
            },
            {
                'name': 'dlvPhone',
                'desc': '提货点联系人电话',
                'example': '13766660000',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 236,
            },
            {
                'name': 'promoteUserName',
                'desc': '所属推广员',
                'example': '推广员A',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 240,
            },
            {
                'name': 'leaderName',
                'desc': '所属团长',
                'example': '李小红',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 246,
            },
            {
                'name': 'grandSonName',
                'desc': '所属帮卖团长',
                'example': '所属帮卖团长',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 248,
            },
            {
                'name': 'leaderId',
                'desc': '团长ID',
                'example': '001',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 257,
            },
            {
                'name': 'leaderPhone',
                'desc': '团长联系电话',
                'example': '13766000000',
                'selected': False,
                'simpleModelDefault': False,
                'sortNum': 267,
            },
            {
                'name': 'buyerRemark',
                'desc': '参与人备注',
                'example': '需要送货上门',
                'selected': True,
                'simpleModelDefault': True,
                'sortNum': 277,
            },
            {
                'name': 'salesRemark',
                'desc': '发起人备注',
                'example': '延期发货',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 287,
            },
            {
                'name': 'customizedInput',
                'desc': '自定义填写项',
                'example': '007',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 297,
            },
            {
                'name': 'goodsList',
                'desc': '商品列表',
                'example': '',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 307,
            },
            {
                'name': 'asType',
                'desc': '售后类型',
                'example': '退货退款',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 310,
            },
            {
                'name': 'asStatusNew',
                'desc': '售后状态(新)',
                'example': '售后成功',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 311,
            },
            {
                'name': 'asAddress',
                'desc': '售后地址',
                'example': '广东省广州市海珠区xxx',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 312,
            },
            {
                'name': 'asCourierCompany',
                'desc': '退货快递公司',
                'example': 'xxx公司',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 313,
            },
            {
                'name': 'asCourierNumber',
                'desc': '退货快递单号',
                'example': 'SF121564',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 314,
            },
            {
                'name': 'asContent',
                'desc': '售后原因',
                'example': '7天无理由',
                'selected': False,
                'simpleModelDefault': True,
                'sortNum': 315,
            },
        ],
    }

    response = requests.post('https://apipc.qunjielong.com/order-export/api/pc/do_export_v2', headers=headers, json=json_data)
    #print(response.json())
    #print (response.json())
    tasknum=response.json()['data']['taskId']
    #print(tasknum)
    return tasknum

# 2304080314677906
#'PsHG7Z8_bsSfpBS_13418e71'
#print(get_exp('PsHG7Z8_bsSfpBS_13418e71',2304060731505403))
